version: "3.8"

services:
  product-db:
    image: postgres:latest
    container_name: postgres
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: avanish7080
    volumes:
      - postgres-data:/var/lib/potgresql/data
    networks:
      - myNetwork

  product-service:
    image: avanish0210/product-service
    container_name: product-service
    ports:
      - "8080:8080"
    networks:
      - myNetwork
    depends_on:
      - product-db

volumes:
  postgres-data:

networks:
  myNetwork:
