spring.application.name=ChachingApp

spring.datasource.url=jdbc:postgresql://localhost:5432/Caching
spring.datasource.username=postgres
spring.datasource.password=avanish7080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#redis configuration
#spring.data.redis.host=localhost
#spring.data.redis.port=6379

spring.data.redis.host=redis-13469.crce283.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=13469
spring.data.redis.password=Tjverot3zLNALwc64h8pHUmOCouJYxFM
spring.data.redis.ssl.enabled=false