services:
  postgres:
    image: pgvector/pgvector:pg18
    container_name: pgvector-local
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-test-vector-db
      TZ: Asia/Kolkata
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/18/main
    restart: unless-stopped

volumes:
  pgdata: